import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Pagination from '../../../components/Pagination'
import UniNameCard from '../../../components/UniNameCard'
import { Col, Container, Row } from 'react-bootstrap'

export default function Index({ data, API_URL, testo }) {
  console.log(API_URL)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <Pagination
          //   path='/people/page/'
          spaceing='2px'
          next={data.next}
          pageNumber={data.count}
          previous={data.previous}
        />
        <Container>
          <Row>
            <Col lg={4} md={4} sm={4} sm={12}>
              <h1>Test</h1>
            </Col>

            {data.results.map((person, index) => (
              //   <Link
              //     key={index}
              //     href={`/people${person.url.slice(person.url.indexOf(29) + 29)}`}
              //   >
              //     <h1>
              //       <div>{person.name}</div>
              //       <div></div>
              //     </h1>
              //   </Link>
              <UniNameCard key={index} API_URL={API_URL} person={person} />
            ))}
          </Row>
        </Container>
      </div>
    </div>
  )
}

export async function getServerSideProps(context) {
  const { id } = context.query

  const { API_URL } = process.env

  const testo = context.params

  const res = await fetch(`${API_URL}/people/?page=${id}`)
  const data = await res.json()

  if (!data) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: { data, API_URL, testo },
  }
}
