import Head from 'next/head'
import Link from 'next/link'
import Person from '../../components/people/person'
import Image from 'next/image'
import { Col, Container, Row } from 'react-bootstrap'
import UniNameCard from '../../components/UniNameCard'
import MoreLink from '../../components/MorePageBtn'

export default function Index({ data, API_URL }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <Container>
          <Row>
            <Col lg={4} md={4} sm={6}>
              <h1>Hello wolre</h1>
            </Col>
            {data.results.map((person, index) => (
              <UniNameCard key={index} API_URL={API_URL} person={person} />
            ))}
          </Row>
        </Container>
      </div>
      <MoreLink />
    </div>
  )
}

export async function getServerSideProps() {
  const { API_URL } = process.env

  const res = await fetch(`${API_URL}/people`)
  const data = await res.json()

  if (!data) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: { data, API_URL },
  }
}
