import Head from 'next/head'
import Link from 'next/link'
import Person from '../../components/people/person'
import Image from 'next/image'

export default function Index({ data, API_URL }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        {data.results.map((vehicle, index) => (
          <Link
            key={index}
            href={`/vehicles${vehicle.url.slice(vehicle.url.indexOf(31) + 31)}`}
          >
            <h1>
              <div>{vehicle.name}</div>
              <div></div>
            </h1>
          </Link>
        ))}
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const { API_URL } = process.env

  const res = await fetch(`${API_URL}/vehicles`)
  const data = await res.json()

  if (!data) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: { data, API_URL },
  }
}
